#!/usr/bin/env python3
# Copyright (c) 2020 Mobvoi Inc (Binbin Zhang)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============================================================================
# R067 重建物:modules/wenet/utils/cmvn.cp310-win_amd64.pyd
#   source_sha256 = a7b77d55233d6808042c6d25899f6175c0b390134b9aad728f8544eaace6bac2
#
# 二进制出处(逐行):
#   [pyd imports.txt]  cmvn._load_json_cmvn / cmvn._load_kaldi_cmvn /
#                      cmvn.load_cmvn / cmvn.py / numpy / python310.dll
#   [pyd strtab]       ' Load the json format cmvn stats file and calculate cmvn'
#                      ' Load the kaldi format cmvn stats file and calculate cmvn'
#                      'mean_stat' 'var_stat' 'frame_num' 'cmvn_stats'
#                      'feat_dim' 'variance' 'cmvn_file' 'json_cmvn_file'
#                      'kaldi_cmvn_file' 'init cmvn' "PyInit_cmvn"
#                      'kaldi cmvn binary file is not supported, please '
#                      'recompute it by: compute-cmvn-stats --binary=false  '
#                      'scp:feats.scp global_cmvn'
#                      (strtab 全量导出见报告 §3;无 "(line N)" 行号表项)
#   [runtime ev]       evidence/modules/wenet__utils__cmvn/runtime/*.json
#                      函数签名 (_load_json_cmvn(json_cmvn_file) /
#                      _load_kaldi_cmvn(kaldi_cmvn_file) / load_cmvn(cmvn_file,
#                      is_json)),module_dir 含 json/logging/math/np/sys
#   [E1]               evidence/modules/wenet__utils__cmvn/probes/probe_cmvn.py
#                      + probe_cmvn_out.json
#   [upstream]         wenet-e2e/wenet @d170596 wenet/utils/cmvn.py(逐行同构)
#
# [本地改动] 上游 cmvn.py 只 import json/math/numpy,但 _load_kaldi_cmvn 的
#   二进制分支用了 logging.error + sys.exit(1);本 pyd 的 module_dir 实测含
#   logging 与 sys(E1 probe_cmvn :: has_logging/has_sys → module),
#   故本重建物显式 import logging / import sys(否则该分支 NameError)。
# ============================================================================

import json
import logging
import math
import sys

import numpy as np


def _load_json_cmvn(json_cmvn_file):
    """ Load the json format cmvn stats file and calculate cmvn

    Args:
        json_cmvn_file: cmvn stats file in json format

    Returns:
        a numpy array of [means, vars]
    """
    # [E1 probe_cmvn :: _load_json_cmvn](fixture 值 [10,20,30]/[4,9,16]/count=2
    #   → mean [5,10,15],var 全 1e10)与上游逐行一致。
    with open(json_cmvn_file) as f:
        cmvn_stats = json.load(f)

    means = cmvn_stats['mean_stat']
    variance = cmvn_stats['var_stat']
    count = cmvn_stats['frame_num']
    for i in range(len(means)):
        means[i] /= count
        variance[i] = variance[i] / count - means[i] * means[i]
        # [E1] variance<1e-20 → 1e-20 → 1/sqrt → 1e10(实测 10000000000.0)
        if variance[i] < 1.0e-20:
            variance[i] = 1.0e-20
        variance[i] = 1.0 / math.sqrt(variance[i])
    cmvn = np.array([means, variance])
    return cmvn


def _load_kaldi_cmvn(kaldi_cmvn_file):
    """ Load the kaldi format cmvn stats file and calculate cmvn

    Args:
        kaldi_cmvn_file:  kaldi text style global cmvn file, which
           is generated by:
           compute-cmvn-stats --binary=false scp:feats.scp global_cmvn

    Returns:
        a numpy array of [means, vars]
    """
    means = []
    variance = []
    with open(kaldi_cmvn_file, 'r') as fid:
        # kaldi binary file start with '\0B'
        # [E1 probe_cmvn :: _load_kaldi_cmvn_binary] 首 2 字符 "\x00B" →
        #   SystemExit(1),stderr = 'ERROR:root:kaldi cmvn binary file is not
        #   supported, please recompute it by: compute-cmvn-stats
        #   --binary=false  scp:feats.scp global_cmvn'(注意 'false' 与 'scp'
        #   之间是两个空格,来自源码相邻字面量拼接)。
        if fid.read(2) == '\0B':
            logging.error('kaldi cmvn binary file is not supported, please '
                          'recompute it by: compute-cmvn-stats --binary=false '
                          ' scp:feats.scp global_cmvn')
            sys.exit(1)
        fid.seek(0)
        arr = fid.read().split()
        # [E1 probe_cmvn :: _load_kaldi_cmvn_bad] 非 kaldi 文本 → AssertionError
        assert (arr[0] == '[')
        assert (arr[-2] == '0')
        assert (arr[-1] == ']')
        feat_dim = int((len(arr) - 2 - 2) / 2)
        for i in range(1, feat_dim + 1):
            means.append(float(arr[i]))
        count = float(arr[feat_dim + 1])
        for i in range(feat_dim + 2, 2 * feat_dim + 2):
            variance.append(float(arr[i]))

    for i in range(len(means)):
        means[i] /= count
        variance[i] = variance[i] / count - means[i] * means[i]
        if variance[i] < 1.0e-20:
            variance[i] = 1.0e-20
        variance[i] = 1.0 / math.sqrt(variance[i])
    cmvn = np.array([means, variance])
    return cmvn


def load_cmvn(cmvn_file, is_json):
    # [E1 probe_cmvn :: load_cmvn_json / load_cmvn_is_json_truthy(1) /
    #   load_cmvn_is_json_falsy(0) / load_cmvn_is_json_none(None)]
    #   → is_json 走真值判断;返回 tuple(np.ndarray, np.ndarray)。
    if is_json:
        cmvn = _load_json_cmvn(cmvn_file)
    else:
        cmvn = _load_kaldi_cmvn(cmvn_file)
    return cmvn[0], cmvn[1]
